version: '3.3'

services:

  client:
    build:
      context: ./client
    restart: always
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
      GROUND_STATION_HOST: 'http://socketio.ffaerber.com'
    depends_on:
      - message-bus

  message-bus:
    build:
      context: ./message-bus
    restart: always

  thunderborg:
    build:
      context: ./thunderborg
    restart: always
    environment:
      MESSAGE_BUS_HOST: 'message-bus'
    depends_on:
      - message-bus

  gps:
    build:
      context: ./gps
    restart: always
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
      DEVICE: '/dev/ttyUSB0'
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - message-bus

  # camera:
  #   image: mhiro2/rpi-ffmpeg:3.3
  #   command: '-f video4linux2 -i /dev/video0 -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -s 640x360 -r 30 -b:v 500k -bufsize 500k'
  #   restart: always
  #   devices:
  #     - "/dev/video0:/dev/video0"
