version: '3.3'

services:

  client:
    build:
      context: ./client
    restart: always
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
      GROUND_STATION_HOST: 'http://socketio.ffaerber.com'
    depends_on:
      - message-bus

  thunderborg:
    build:
      context: ./thunderborg
    restart: always
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    depends_on:
      - message-bus
    deploy:
      resources:
        limits:
          memory: 50M

  # gps:
  #   build:
  #     context: ./gps
  #   restart: always
  #   environment:
  #     MESSAGE_BUS_HOST: 'mqtt://message-bus'
  #     DEVICE: '/dev/ttyUSB0'
  #   devices:
  #     - "/dev/ttyUSB0:/dev/ttyUSB0"
  #   depends_on:
  #     - message-bus

  message-bus:
    build:
      context: ./message-bus
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
