version: '3.3'

services:

  client:
    build:
      context: ./client
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
      GROUND_STATION_HOST: 'http://socketio.ffaerber.com'
    depends_on:
      - message-bus

  gps:
    build:
      context: ./gps
    environment:
      MESSAGE_BUS_HOST: 'mqtt://message-bus'
      DEVICE: '/dev/ttyUSB0'
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - message-bus

  message-bus:
    build:
      context: ./message-bus
